
FILE_FORMAT = "ogr"
SRID = 7855
H3_RESOLUTION = 10

SOURCE_RAW_DATA_PATH = 'dbfs:/FileStore/tables/'
EXPORT_FILE_PATH = '/Volumes/dbdemos/benchjam_geospatial/output/'

# DB Configs
PARTITION_KEY = "road_type"

CATALOG_NAME = "dbdemos"
SCHEMA_NAME = "benchjam_geospatial"

SILVER_TABLE_ROADS = "silver_roads"
SILVER_TABLE_LGA = "silver_lga"
SILVER_TABLE_TELEMATICS = "silver_telematics"
SILVER_TABLE_ROADS_LGA_JOINED = "silver_roads_lga"
SILVER_TABLE_ROADS_LGA_TELEMATICS_JOINED = "silver_lga_roads_telematics"
GOLD_ROADS_MEAN_SPEED = 'gold_roads_mean_speed'

FILE_EXPORT_DRIVER = 'GeoJSON'

FULL_SILVER_ROADS_PATH = f"{CATALOG_NAME}.{SCHEMA_NAME}.{SILVER_TABLE_ROADS}"
FULL_SILVER_LGA_PATH = f"{CATALOG_NAME}.{SCHEMA_NAME}.{SILVER_TABLE_LGA}"
FULL_SILVER_TELEMATICS_PATH = f"{CATALOG_NAME}.{SCHEMA_NAME}.{SILVER_TABLE_TELEMATICS}"
FULL_SILVER_ROADS_LGA_JOINED_PATH = f"{CATALOG_NAME}.{SCHEMA_NAME}.{SILVER_TABLE_ROADS_LGA_JOINED}"
FULL_SILVER_LGA_ROADS_TELEMATICS_JOINED_PATH = f"{CATALOG_NAME}.{SCHEMA_NAME}.{SILVER_TABLE_ROADS_LGA_TELEMATICS_JOINED}"

# KNN Configs
EXPERIMENT_PATH = "/Shared/bechjam_geospatial"
RUN_ROOT_NAME = "spatial_knn"
DISTANCE_THRESHOLD = 1.0
K_NEIGHBORS = 5
APPROX = False
MAX_ITER = 10
EARLY_STOP_ITER = 3
LANDMARKS_ROW_ID = "OBJECTID"
CANDIDATE_ROW_ID = "road_pid"
LANDMARKS_FEAT_COL = "geom_0"
CANDIDATES_FEAT_COL = "roads_geom_0"
CHECKPOINT_TABLE_PREFIX = "checkpoint_table_knn"
CHECKPOINT_DIR = "dbfs:/tmp/mosaic/benchjam_geospatial/checkpoints"